# Copyright 2018 
# Ipan Ardian <ipan.software@gmail.com>
# Apache License 2.0

version: '3'
services:
    web:
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        ports:
            - "8080:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        depends_on:
            - php
            - mysql
    php:
        image: crunchgeek/php-fpm:${PHP_VERSION}
        container_name: php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        ports:
            - "9090:9000"
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    memcached:
        image: memcached:${MEMCACHED_VERSION}
        container_name: memcached
        container_name: ${MEMCACHED_HOST}
        ports:
            - 11212:11211
